# Generated by Django 4.1 on 2023-03-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='photo',
            field=models.FileField(default='', upload_to='cloth_pics'),
            preserve_default=False,
        ),
    ]
