# Generated by Django 4.1 on 2023-04-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_clothes_categories_clothes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
