# Generated by Django 4.1.7 on 2023-03-01 17:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateField()),
                ('cothes_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clothes.clothes')),
            ],
            options={
                'db_table': 'customer_clothes',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.CharField(max_length=3)),
                ('permanent_address', models.CharField(max_length=300)),
                ('resident_address', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'customers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('amount_left', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('customer_clothes_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.customer_clothes')),
            ],
            options={
                'db_table': 'customer_payment',
            },
        ),
        migrations.AddField(
            model_name='customer_clothes',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.customers'),
        ),
    ]
