# Generated by Django 4.1 on 2023-03-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='resident_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
