# Generated by Django 4.1 on 2023-04-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_resident_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_clothes',
            old_name='purchased_date',
            new_name='ordered_date',
        ),
        migrations.AddField(
            model_name='customer_clothes',
            name='is_ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
