# Generated by Django 4.1 on 2023-04-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_rename_photo_clothes_photo1_clothes_photo2_and_more'),
        ('customers', '0006_customer_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=6)),
                ('size', models.CharField(max_length=4)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clothes.clothes')),
            ],
            options={
                'db_table': 'Customer_Orders',
            },
        ),
    ]
