# Generated by Django 4.1 on 2023-04-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_orders',
            name='is_ordered',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
