# Generated by Django 4.1 on 2023-04-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_orders_is_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_mail', models.EmailField(max_length=254)),
                ('joining_date', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'Subscribe',
            },
        ),
    ]
