# Generated by Django 4.1 on 2023-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_subscribe_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='joining_date',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
