# Generated by Django 4.1 on 2023-04-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_subscribe_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='joining_date',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
